#!/usr/bin/env python
"""Generate logs/INDEX.md -- a navigable table of every SLURM log.

WHY AN INDEX AND NOT A CLEANUP.  A few hundred flat Report-*.out files are hard
to scan, which reads as clutter -- but deleting them is the wrong fix twice
over.  They are all git-tracked, so removing one from the working tree reclaims
NOTHING (.git already carries it), and a history rewrite on a pushed shared repo
is not a trade worth making for ~88 MB.  And several logs are the ONLY source
for a recorded number: the P2.3 cells ran with `diag_interval=0`, so
`Report-13297370/71.out` hold the only copy of the paired training trace the
headline result was read from, and `tools/compare_arms.py --log` reads them BY
NAME.  Prune those and the result stops being reproducible.

So: index, do not prune.

No GPU, no torch, safe to re-run any time:

    python tools/index_logs.py
"""
from __future__ import annotations

import datetime
import glob
import os
import re
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """# Log index

Generated by `tools/index_logs.py`.  Re-run it after pulling new logs.

**Nothing here is safe to delete on size grounds.**  Every file is git-tracked,
so removing one from the working tree reclaims nothing -- `.git` already carries
it -- and only costs the provenance of whatever result it backs.  Several are
the ONLY source for a recorded number: `Report-13297370.out` and
`Report-13297371.out` are the P2.3 cells, and because those ran with
`diag_interval=0` they hold the only copy of the paired training trace.
`tools/compare_arms.py --log` reads them by name and `p23_cells_prereg.md` S5
cites them.

| date | job | name | status | size |
|---|---|---|---|---|"""


def classify(tail: str) -> str:
    """What happened to this job, from the end of its own log."""
    if "CANCELLED" in tail:
        return "cancelled"
    if re.search(r"DUE TO TIME LIMIT", tail, re.I):
        return "timeout"
    if re.search(r"\bOutOfMemoryError\b|CUDA out of memory", tail):
        return "OOM"
    if "Begin Slurm Epilog" in tail:
        return "completed"
    # No epilog and no kill message: the job is still running, or the log was
    # copied off the cluster mid-flight.  Not an error, but not a result either.
    return "no epilog"


def _size(n: int) -> str:
    return "%.1f MB" % (n / 1048576) if n > 1048576 else "%d KB" % (n // 1024)


def scan():
    rows = []
    for path in glob.glob(os.path.join(REPO, "logs", "Report-*.out")):
        jid = os.path.basename(path)[len("Report-"):-len(".out")]
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = fh.read()
        except OSError:
            continue
        head, tail = text[:4000], text[-4000:]
        m = re.search(r"Job name:\s*(\S+)", head)
        name = m.group(1) if m else ""
        date = ""
        m = re.search(r"Begin Slurm Prolog:\s*(\S+)", head)
        if m:
            try:
                date = datetime.datetime.strptime(
                    m.group(1), "%b-%d-%Y").strftime("%Y-%m-%d")
            except ValueError:
                date = m.group(1)
        rows.append((date, jid, name, classify(tail), os.path.getsize(path)))
    # Sort by date then job id, so the table reads as a timeline.
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


def main() -> int:
    rows = scan()
    out = [HEADER]
    for date, jid, name, status, size in rows:
        out.append("| %s | %s | %s | %s | %s |"
                   % (date or "-", jid, name or "-", status, _size(size)))
    counts = Counter(r[3] for r in rows)
    out += ["", "## Totals", "", "- %d logs" % len(rows)]
    out += ["- %s: %d" % (k, v) for k, v in counts.most_common()]

    path = os.path.join(REPO, "logs", "INDEX.md")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s  (%d logs)" % (os.path.relpath(path, REPO), len(rows)))
    for k, v in counts.most_common():
        print("  %-12s %d" % (k, v))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
